### ISSUE TITLE
schema propsal

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_hq#1]
Name:  tripal_hq_submissions

fields

uid, type (edit/credit), status (approve, deny, pending), date created (maybe?), data (serialized array), entity_id (for linking to approved, or preexisting record for edits)

**Comment by almasaeed2010** [comment]
date_created is part of the entity so it'll be already serialized I think.

Otherwise I think this is perfect!

**Comment by bradfordcondon** [comment]
yeah but then you'd hae to unseralize all data in order to display in a table?  Dont need it to sort because you can sort by p_id....

**Comment by almasaeed2010** [comment]
I see yeah. I don't see an issue with adding a timestamp 👍

**Comment by almasaeed2010** [comment]
In that case, should we add title?

**Comment by bradfordcondon** [comment]
yes! 

Is that all we'd nee for both the admin and user dashboard?

What about down teh road with Chado permission integration?  I imagine a linker table linking submission id to however you set up permission ie via organism or project.    Too hard to think about putting in this table.

**Comment by almasaeed2010** [comment]
yes a primary key (id) should exist

**Comment by laceysanderson** [comment]
Looks good to me as well :-)

**Comment by almasaeed2010** [comment]
I suggest changing timestamp to `created_at` and `updated_at` since it currently doesn't indicate it's a timestamp for what. What do you think?

**Comment by bradfordcondon** [comment]
mmmm yeah ok.  but we need to be clear that if the same record is updated later, thats a new entry.  Updated_at would apply to users who propose content, then change their proposal via edit.

If a user proposes an edit to an existing piece of content, then that just has a created_at stamp and no updated_at.  right?

**Comment by almasaeed2010** [comment]
you are right. the updated_at gets inserted only when that submission is currently pending has been edited by submitter.

**Comment by almasaeed2010** [comment]
I think it's nice to have the updated at becuase admins can tell if a user has submitted changes they requested.

**Comment by bradfordcondon** [comment]
thanks for input/discussion all
