### ISSUE TITLE
annotations widget gives ajax error

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_hq#17]
![screen shot 2018-10-09 at 4 04 38 pm](https://user-images.githubusercontent.com/7063154/46695260-14aea180-cbdd-11e8-97a3-da1ab9ac2784.png)

I dont know why its looking for an uniquename column for the features table.

**Comment by almasaeed2010** [comment]
Annotations work for me. All of the ajac fields in fact work fine for me. Is this a specific entity type?

<img width="746" alt="screen shot 2018-10-10 at 9 43 02 am" src="https://user-images.githubusercontent.com/1512664/46740467-e67aa180-cc70-11e8-85e6-92f756a076a4.png">

**Comment by bradfordcondon** [comment]
interesting.  this was analysis i believe.  the errors didnt make sense since it was "uniquename"" not found which is not part of the analysis schema...

**Comment by almasaeed2010** [comment]
Yep analysis is the culprit.
<img width="495" alt="screen shot 2018-10-10 at 9 45 52 am" src="https://user-images.githubusercontent.com/1512664/46740625-4e30ec80-cc71-11e8-926f-83309969d5e2.png">

**Comment by bradfordcondon** [comment]
lets confirm this isnt a problem in the regular field first :)

**Comment by bradfordcondon** [comment]
i also get it for biomaterials
<img width="899" alt="screen shot 2018-10-10 at 6 17 06 pm" src="https://user-images.githubusercontent.com/7063154/46769129-c373e000-ccb8-11e8-89fb-81d8714f570c.png">

**Comment by almasaeed2010** [comment]
Does feel like a core issue to you? I've been looking it all morning but  I can't figure out why it would happen on our form but no the core form. We follow the exact same steps to construct the form. The only difference is the URI and I don't see how that's relevant.

**Comment by bradfordcondon** [comment]
we have hunted this down to understand that the SBO__RELATIONSHIP widget is causing this error.  This widget is not visible on core, but is visible in tripal_hq.  disabling this widget fixes the ajax errors in all other widgets.


The relationship widget is extra squirrely because it immediately returns after the parent invocation:

```php

  /**
   *
   * @see TripalFieldWidget::form()
   */
  public function form(&$widget, &$form, &$form_state, $langcode, $items, $delta, $element) {
    parent::form($widget, $form, $form_state, $langcode, $items, $delta, $element);

    // TODO: make this widget deal better with the various relationship
    // tables. See the load function as it does a better job of this.
    return;

```

@laceysanderson any chance you have a clue whats going on?

**Comment by almasaeed2010** [comment]
PR #29 fixes this issue as well. All fields functioned properly on my end.

**Comment by almasaeed2010** [comment]
I'll close but if the issue shows up again please reopen.
