### ISSUE TITLE
approving record gives page not found

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_hq#18]
clicking submit redirects to:

http://localhost:8083/tripal_hq/admin/approve/1
which is not defined and not in the `.module` file.  The status of the record is not updated to approved but is still pending afterwards.

**Comment by bradfordcondon** [comment]
rejct also not defined.  http://localhost:8083/tripal_hq/admin/reject/1

have we just not set these up yet?

**Comment by almasaeed2010** [comment]
Yep haven’t worked on them yet. Was planning to but got interrupted mid way. I’ll push tomorrow I already have half the code ready.

**Comment by bradfordcondon** [comment]
ok no worries.  should i only be testing the edit form then?

**Comment by almasaeed2010** [comment]
see #19

**Comment by almasaeed2010** [comment]
Merged
