### ISSUE TITLE
Field level permissions

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/tripal_hq#21]
It'd be nice if the admin could choose which fields are visible and editable to the end user.

**Comment by bradfordcondon** [comment]
I think its **critical** for the functionality of this module.

https://github.com/tripal/tripal/issues/703

Could you please weigh in with your support @almasaeed2010 ?  With stephen out of town this month it might have to wait but @laceysanderson has already chimed in so I think we could think about adding field-level permissions at the core level.

**Comment by almasaeed2010** [comment]
Haven't tested this yet but I think there is a pretty safe and easy way to do the field permissions. 

- [ ] Build a UI for the admin to choose fields based on the bundle (we'll need a DB table for this)
- [ ] Loop through the form that tripal generates and convert any unpermitted field to `hidden`

**Comment by almasaeed2010** [comment]
Alright I'll take a look at the issue @bradfordcondon

**Comment by almasaeed2010** [comment]
Yeah I think if this is done on core level, we wouldn't have to hack a solution as I mentioned above.

**Comment by almasaeed2010** [comment]
i will add this question to core but for now:

What happens to collections when this is implemented?

**Comment by bradfordcondon** [comment]
see #84
