### ISSUE TITLE
email configuration

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_hq#22]
site-level admin configuration.

![screen shot 2018-10-10 at 11 46 43 am](https://user-images.githubusercontent.com/7063154/46748748-3f066a80-cc82-11e8-87fa-bb3ebe27b990.png)

- [ ] Submission needs to get stored (in a table?  drupal variable?)

- [ ] Default configuration on fresh install should be sane

**Comment by almasaeed2010** [comment]
It's a simple array of key: `email_type` value: `['user', 'admin']` so I think going with a variable for the time being is ok. A migration to a table is always possible later if it get's complicated and/or large.
