### ISSUE TITLE
Paginate results in both and admin and user tables

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/tripal_hq#35]

**Comment by bradfordcondon** [comment]
looks to me like this is done.  pager in the admin and user dashboard, set to 20.

**Comment by bradfordcondon** [comment]
oops, nevermind, i can see thats broken.  

I'm goign to move the query out of the `tripal_hq_submissions` API, since that way we can use the headrs to sort and do the pagination before executing the query instead of a fetchAll.

**Comment by bradfordcondon** [comment]
@almasaeed2010 if your want to keep it in an API then we can have it pass in $headers and return the $query instead of the results...

**Comment by bradfordcondon** [comment]
sorting  in user area:
<img width="1288" alt="screen shot 2018-10-24 at 5 46 56 pm" src="https://user-images.githubusercontent.com/7063154/47463652-d1dff280-d7b4-11e8-9fbc-c93e2dda721b.png">

sorting/tabs in admin area:

<img width="1292" alt="screen shot 2018-10-24 at 5 47 29 pm" src="https://user-images.githubusercontent.com/7063154/47463675-e58b5900-d7b4-11e8-87b0-9fbd2ed903cd.png">
