### ISSUE TITLE
previous pr broke core functionality

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_hq#47]
oops, my bad. now when we submit a proposal, it just creates the entity :P

**Comment by almasaeed2010** [comment]
Can u try clearing cache?

**Comment by bradfordcondon** [comment]
clearing cache resolved.  

What happened was we were no longer altering the form, so it was just standard entity creation/submission.  dpm in our custom submit didnt fire.

let's keep 👁 eyes open for this so we can reproduce and hunt it down if it wasnt a one-off.
