### ISSUE TITLE
clearing cache necessary for the submit to work

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_hq#57]
i ran into this problem again on teh i5k demo site.  it created into chado until i cleared cache.

**Comment by bradfordcondon** [comment]
ok heres my theory:

Submit an organism with an image attached.  It will be created as an entity.

This field is breaking HQ's functionality somehow

**Comment by almasaeed2010** [comment]
Duplicated on my newly installed instance. The image field does break the submission process.
