### ISSUE TITLE
admin dashboard area

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_hq#6]
page is at `/tripal_hq/admin_dash/`.

For admins and content admins to approve/deny chado creation requests.

### Currently

<img width="834" alt="screen shot 2018-10-08 at 4 13 58 pm" src="https://user-images.githubusercontent.com/7063154/46631380-347a9280-cb15-11e8-8c67-427ca37bfe25.png">

### Improvements

* This page should perhaps be a view, so as to provide sorting, filtering, searching.   However, I'm not sure how that would combine with advanced chado permissions we might implement.
* Summarize pending requests?  (IE you have x pending requests to review...)
* Separate table for obsolete requests?
* Title should be either customizable by the site admin, or set based on site title?  Or not be branded by module...

**Comment by bradfordcondon** [comment]
* Should link to the existing entity is the entity exists.  If its an edit on said entity, should link to the proposed new entity. 
  - i think this could be done by checking if entity ID and if data exists.  if ID and no data, then its created, link to the entity.  If ID exists AND there is data, then we're editing.  If no entity ID then we're creating.

**Comment by laceysanderson** [comment]
My thoughts:
- It would be nice to filter the table to see only pending results.
- Maybe you want to make the title more generic, like “Content Submissions”?
- linking to a content preview would be great!
- theme_table can be used for filtering and sorting as well. Views can be nice but isn’t always worth the effort

**Comment by bradfordcondon** [comment]
Yeah i was originally gong to have 2 tables, one for pending and one for everything else.  I could do a type filter dropdown instead.

**Comment by laceysanderson** [comment]
That sounds good too 🙂

**Comment by bradfordcondon** [comment]
- [ ] generic title

- [ ] filtering and sorting on table

- [ ] highlight or promote pending records

**Comment by bradfordcondon** [comment]
![screen shot 2018-11-09 at 1 35 50 pm](https://user-images.githubusercontent.com/7063154/48281377-663c8d00-e424-11e8-9120-4bc061306e03.png)
heres where we are at.

tabs allow easy filtering, and defaulting to pending just shows what needs action

sorting is there.  No filtering but we have an issue for that #36 

So I think im closing this issue, tahnks for input lacey, if you have more please let me know.
