### ISSUE TITLE
Bundle level permissions?

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripal_hq#8]
The site administrator will want to determine which bundles are open to users to propose records for.  

* On install, we can check all bundles defined and create permissions for each. (administer and propose)
* if a new bundle is defined, can we hook into that event and create a permission for it?

**Comment by bradfordcondon** [comment]
Put another way... at the user dashboard, they're going to see a) what stuff they can propose to create, and b) a dashboard of their submitted stuff/status.

**Comment by bradfordcondon** [comment]
after discussion with @almasaeed2010 this is our proposed strategy:

* Programatically create a sepeate permission for each bundle.  IE tripal_hq_user_propose_organism
* Hook into bundle_create to add the permission.
* At the user dashboard, we a) get all permissions registered with our module, b) filter out the non-bundle ones, and c) use `user_access` to check which should display.

**Comment by almasaeed2010** [comment]
This is how tripal does it:
```
function tripal_permissions() {
// Add permissions for each content type.
  $bundles = tripal_get_content_types();
  foreach ($bundles as $bundle) {
    $permissions['view ' . $bundle->name] = array(
      'title' => t('%label: View Content', array('%label' => $bundle->label)),
      'description' => t('Allow the user to view %label content', array('%label' => $bundle->label)),
    );
  }
}
```

I suppose this validates that our method is sound. This way the permissions are defined everytime the cache is cleared and there is no need to `install` anything.

**Comment by almasaeed2010** [comment]
Tripal also uses `user_access` to check permissions. Performance is pretty good for that page so we are good to go there as well:

` if (user_access('propose ' . $bundle->name)) {`

**Comment by almasaeed2010** [comment]
Permissions all set:

<img width="1362" alt="screen shot 2018-10-09 at 10 18 47 am" src="https://user-images.githubusercontent.com/1512664/46675593-c386b980-cbac-11e8-9d15-54df89e77499.png">

And the page now responds to those permissions:

<img width="1552" alt="screen shot 2018-10-09 at 10 17 58 am" src="https://user-images.githubusercontent.com/1512664/46675538-a2be6400-cbac-11e8-921c-d3b743987b8b.png">

I'll submit a PR so we can close this issue.

**Comment by almasaeed2010** [comment]
Ok all working here 👍

**Comment by bradfordcondon** [comment]
I think this is so awesome 👍
